### ISSUE TITLE
SUGGESTION: Increase the world height in the Nether

### ISSUE THREAD

**Issue by GitsurferQwerty** [Stardust-Labs-MC/Amplified-Nether#1]
I was thinking, when using this mod, you can't build on top of the nether roof so I was thinking you can just increase the world height limit in the nether to 320y to -64y so that it would match up with the overworld and you'd get some room on the nether roof to build gold farms, ice highways, etc.

**Comment by catter1** [comment]
Although this is a commonly requested feature, this will not happen. This is because increasing the build height increases lag. But, if you'd like to do it yourself, here's how:

• Download slicedlime's datapack [here](https://github.com/slicedlime/examples).
• Unzip Amplified Nether and navigate to the `/data/minecraft/` directory. Copy the `dimension_type` folder from slicedlime's datapack and stick it here.
• Delete every file in the `dimension_type` directory EXCEPT `the_nether.json`.
• Edit that file and look for `”height”:` and change the value to 320. This will add 64 blocks of air above the bedrock roof.
• If on 1.18/1.18.1 only, find the line that says `"infiniburn": "minecraft:infiniburn_nether"` and remove the `#`.
• Save/exit, rezip Amplified Nether, and load it to your world. Enjoy!

**Comment by GitsurferQwerty** [comment]
So, I realized that I can change the world height of all the dimensions, so I did, but they fail to work. I followed all your steps (except for deleting all files in dimension_type, because I changed overworld, overworld_caves, and the_end, too) and the heights were multiples of 16. Doesn't work though.

**Comment by GitsurferQwerty** [comment]
nvm got it to work. thank you!
