### ISSUE TITLE
[ENHANCEMENT] Increase in build height

### ISSUE THREAD

**Issue by pr13260** [Stardust-Labs-MC/Amplified-Nether#3]
As amplified nether increases nether roof height to 256 (maxing it out).
it stop possibility of creating any nether roof farms which is a huge setback, so if possible please increase the build height of nether roof a few chunks. 
it would be more than appreciated.

**Comment by catter1** [comment]
As per #1, will not be implemented.

But to append to the comment I left on #1, you should instead use this datapack instead of the old instructions: https://github.com/Apollounknowndev/pack-library/tree/main/nether-build-height

That will allow you a higher roof. But this will not be added into base Amplified Nether

**Comment by DeltaV-1** [comment]
Can you give instructions on how to use Apollo's datapack?

**Comment by catter1** [comment]
> Can you give instructions on how to use Apollo's datapack?

You just load it as a normal datapack - make sure it's loaded above Amplified Nether.

Other than that, I'm not going to provide support for it here - you can ask in Apollo's server or on her GitHub
